/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hotel;

import java.time.LocalDate;

public class App {
	public static void main(String[] args) {
		System.out.println(new HotelController(10).findAvailableRoomsOn(LocalDate.now()));
	}
}
